CREATE TABLE `role`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `gmt_create` TIMESTAMP NOT NULL  DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `gmt_modified` TIMESTAMP NOT NULL DEFAULT now() ON UPDATE now() COMMENT '修改时间',
  `role_name` VARCHAR (255) NOT NULL COMMENT '角色名称',
  `descr` VARCHAR (255) NOT NULL COMMENT '描述',
  `resource_ids` VARCHAR (255) COMMENT '资源ids',
  `avaliable` TINYINT (1) COMMENT '是否可用',
  PRIMARY KEY (`id`)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;