CREATE TABLE `verify_code`(
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `gmt_create` TIMESTAMP NOT NULL  DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',
  `gmt_modified` TIMESTAMP NOT NULL DEFAULT now() ON UPDATE now() COMMENT '修改时间',
  `mobile` VARCHAR (128)  COMMENT '手机号' NOT NULL ,
  `code` VARCHAR (128) COMMENT '验证码' NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY (`mobile`)
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;